name: blockchain_flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4  # Maintenir la version actuelle du SDK Dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  firebase_database: ^10.5.7
  provider: ^6.1.2  # Mise à jour de la version de provider pour la null safety
  web3dart: ^2.0.0  # Mettre à jour web3dart vers une version stable compatible avec la null safety
  http: ^0.13.0  # Mise à jour de http vers la version 0.13.0 ou supérieure pour la null safety
  web_socket_channel: ^2.0.0  # Mise à jour de web_socket_channel pour la null safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - src/artifacts/Attendance.json  # Le chemin vers le fichier ABI de votre contrat
